platform :ios, '11.0'

target 'VisilabsExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'VisilabsIOSNew', :path => '../'
  pod 'Eureka'
  pod 'Colorful'
  pod 'CleanyModal'
  pod 'Euromsg'
end

target 'NotificationService' do
#  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'VisilabsIOSNew', :path => '../'
end

